apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sunny-portfolio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/sunnycharkhwal/sunny-portfolio.git
    targetRevision: main
    path: infra/helm/portfolio

  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio

  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration:    10s
        maxDuration: 3m
        factor:      2

  revisionHistoryLimit: 5
